ProjetoTCC/Controllers/ExameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProjetoTCC.Controllers
{
    public class ExameController : Controller
    {
        // GET: Exame
        public ActionResult Index()
        {
            return View();
        }

        // GET: Exame/Details/5
        public ActionResult DetalhesExame(int id)
        {
            Models.Data.ExameData ed = new Models.Data.ExameData();

            return View(ed.DetalhesExame(id));
        }

        public ActionResult ListaExame()
        {
            Models.Data.ExameData ed = new Models.Data.ExameData();

            return View(ed.ListaExame());
        }

        // GET: Exame/Create
        public ActionResult CadastrarExame()
        {
            return View();
        }

        // POST: Exame/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarExame(Models.Exame collection)
        {
            Models.Data.ExameData ed = new Models.Data.ExameData();
            ed.CadastrarExame(collection);

            return RedirectToAction(nameof(ListaExame));
        }

        // GET: Exame/Edit/5
        public ActionResult EditarExame(int id)
        {
            Models.Data.ExameData ed = new Models.Data.ExameData();

            return View(ed.DetalhesExame(id));
        }

        // POST: Exame/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarExame(Models.Exame collection)
        {
            Models.Data.ExameData ed = new Models.Data.ExameData();
            ed.EditarExame(collection);

            return RedirectToAction(nameof(EditarExame));
        }

        // GET: Exame/Delete/5
        public ActionResult DeletarExame(int id)
        {
            Models.Data.ExameData ed = new Models.Data.ExameData();

            return View(ed.DetalhesExame(id));
        }

        // POST: Exame/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarExame(int id, IFormCollection collection)
        {
            Models.Data.ExameData ed = new Models.Data.ExameData();
            ed.DeletarExame(id);

            return RedirectToAction(nameof(ListaExame));
        }
    }
}

ProjetoTCC/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProjetoTCC.Controllers
{
    public class MedicoController : Controller
    {
        // GET: Medico
        public ActionResult Index()
        {
            return View();
        }

        // GET: Medico/Details/5
        public ActionResult DetalhesMedico(int id)
        {
            Models.Data.MedicoData md = new Models.Data.MedicoData();

            return View(md.DetalhesMedico(id));
        }

        public ActionResult ListaMedico()
        {
            Models.Data.MedicoData td = new Models.Data.MedicoData();

            return View(td.ListaMedico());
        }

        // GET: Medico/Create
        public ActionResult CadastrarMedico()
        {
            return View();
        }

        // POST: Medico/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarMedico(Models.Medico collection)
        {
            Models.Data.MedicoData md = new Models.Data.MedicoData();
            md.CadastrarMedico(collection);

            return RedirectToAction(nameof(ListaMedico));
        }

        // GET: Medico/Edit/5
        public ActionResult EditarMedico(int id)
        {
            Models.Data.MedicoData md = new Models.Data.MedicoData();
            
            return View(md.DetalhesMedico(id));
        }

        // POST: Medico/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarMedico(Models.Medico collection)
        {
            Models.Data.MedicoData md = new Models.Data.MedicoData();
            md.EditarMedico(collection);

            return RedirectToAction(nameof(ListaMedico));
        }

        // GET: Medico/Delete/5
        public ActionResult DeletarMedico(int id)
        {
            Models.Data.MedicoData md = new Models.Data.MedicoData();

            return View(md.DetalhesMedico(id));
        }

        // POST: Medico/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarMedico(int id, IFormCollection collection)
        {
            Models.Data.MedicoData md = new Models.Data.MedicoData();
            md.DeletarMedico(id);

            return RedirectToAction(nameof(ListaMedico));
        }
    }
}

ProjetoTCC/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProjetoTCC.Controllers
{
    public class PacienteController : Controller
    {
        // GET: Paciente
        public ActionResult Index()
        {
            return View();
        }

        // GET: Paciente/Details/5
        public ActionResult DetalhesPaciente(int id)
        {
            Models.Data.PacienteData cd = new Models.Data.PacienteData();

            return View(cd.DetalhesPaciente(id));
        }

        public ActionResult ListaPaciente()
        {
            Models.Data.PacienteData td = new Models.Data.PacienteData();

            return View(td.ListaPaciente());
        }

        // GET: Paciente/Create
        public ActionResult CadastrarPaciente()
        {
            return View();
        }

        // POST: Paciente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarPaciente(Models.Paciente collection)
        {
            Models.Data.PacienteData pacienteData = new Models.Data.PacienteData();
            pacienteData.CadastrarPaciente(collection);

            return RedirectToAction(nameof(ListaPaciente));
        }
    

        // GET: Paciente/Edit/5
        public ActionResult EditarPaciente(int id)
        {
        Models.Data.PacienteData pd = new Models.Data.PacienteData();

        return View(pd.DetalhesPaciente(id));
        }

        // POST: Paciente/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarPaciente(int id, Models.Paciente collection)
        {
        Models.Data.PacienteData pacienteData = new Models.Data.PacienteData();
        pacienteData.EditarPaciente(collection);

        return RedirectToAction(nameof(EditarPaciente));
        }
        

        // GET: Paciente/Delete/5
        public ActionResult DeletarPaciente(int id)
        {
            return View();
        }

        // POST: Paciente/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarPaciente(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetoTCC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoTCC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CliniCare</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastrar<!--span class="caret"></!--span--></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Paciente" asp-action="CadastrarPaciente">Paciente</a></li>
                            <li><a asp-area="" asp-controller="Medico" asp-action="CadastrarMedico">Médico</a></li>
                            <li><a asp-area="" asp-controller="Exame" asp-action="CadastrarExame">Exames</a></li>
                            <li><a asp-area="" asp-controller="Anamneses" asp-action="CadastrarAnamneses">Anamneses</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Agenda">Agenda</a></li>

                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consultar<!--span class="caret"></!--span--></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Paciente" asp-action="DetalhesPaciente">Paciente</a></li>
                            <li><a asp-area="" asp-controller="Medico" asp-action="DetalhesMedico">Médico</a></li>
                            <li><a asp-area="" asp-controller="Exame" asp-action="DetalhesExame">Exames</a></li>
                            <li><a asp-area="" asp-controller="Anamneses" asp-action="DetalhesAnamneses">Anamneses</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Estoque</a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Cadastrar" asp-action="CadastrarEstoque">Cadastrar</a></li>
                            <li><a asp-area="" asp-controller="Deletar" asp-action="DeletarEstoque">Deletar</a></li>
                            <li><a asp-area="" asp-controller="Detalhes" asp-action="DetalhesEstoque">Detalhes</a></li>
                            <li><a asp-area="" asp-controller="Editar" asp-action="EditarEstoque">Editar</a></li>
                        </ul>
                    </li>

                    <li><a asp-area="" asp-controller="Home" asp-action="Pagamento">Pagamento</a></li>
                    
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Omega IT. Todos os diretos reservados.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>